import test from 'node:test';
import assert from 'node:assert/strict';
import {StatusController} from '../controller.mjs';
const tick=()=>new Promise(r=>setTimeout(r,15));
function setup(){const frames=[],abort=new AbortController();let cancels=0;const agent={id:'a',cancel(){cancels++;abort.abort();}};const exec={agent,callId:'one',name:'mcp__cua_native__set_value',arguments:{pid:123,window_id:456,text:'PRIVATE_INPUT'},signal:abort.signal};return{frames,abort,agent,exec,monitor:new StatusController(s=>frames.push(s)),cancels:()=>cancels};}
test('pause blocks next dispatch, resume releases once',async()=>{const x=setup();x.monitor.begin(x.exec);x.monitor.togglePause();let dispatched=0;const pending=x.monitor.gate(x.exec).then(()=>dispatched++);await tick();assert.equal(dispatched,0);x.monitor.togglePause();await pending;assert.equal(dispatched,1);assert.equal(x.frames.at(-1).state,'running');});
test('stop cancels participating agent and never dispatches paused action',async()=>{const x=setup();x.monitor.begin(x.exec);x.monitor.togglePause();const pending=x.monitor.gate(x.exec);x.monitor.stop();await assert.rejects(pending,/STOPPED/);assert.equal(x.cancels(),1);assert.equal(x.frames.at(-1).state,'stopped');});
test('caller cancellation releases pause; no stranded promise',async()=>{const x=setup();x.monitor.begin(x.exec);x.monitor.togglePause();const pending=x.monitor.gate(x.exec);x.abort.abort();await assert.rejects(pending,/STOPPED/);assert.equal(x.monitor.waiters.size,0);});
test('same tool call ids across agents stay independent',async()=>{const x=setup();const other={...x.exec,agent:{id:'b',cancel(){}}};x.monitor.begin(x.exec);x.monitor.begin(other);assert.equal(x.monitor.calls.size,2);x.monitor.result(x.exec,{isError:false});assert.equal(x.monitor.calls.size,1);assert.equal(x.frames.at(-1).agentId,'b');});
test('overlay omits input values and raw errors; observed title retained',async()=>{const x=setup();x.monitor.begin(x.exec);x.monitor.result(x.exec,{isError:false,value:{structuredContent:{window_title:'测试窗口',pid:123,window_id:456},content:[]}});x.exec.callId='two';x.monitor.begin(x.exec);assert.equal(x.frames.at(-1).target,'测试窗口');x.monitor.result(x.exec,{isError:true,content:[{type:'text',text:'SECRET_ERROR'}]});assert.equal(x.frames.at(-1).state,'error');assert.doesNotMatch(JSON.stringify(x.frames),/PRIVATE_INPUT|SECRET_ERROR/);});
test('stop remains usable between calls; idle releases agent and pause',async()=>{const x=setup();x.monitor.begin(x.exec);await x.monitor.gate(x.exec);x.monitor.result(x.exec,{isError:false});assert.equal(x.frames.at(-1).active,true);x.monitor.stop();assert.equal(x.cancels(),1);x.monitor.idle(x.agent);assert.equal(x.frames.at(-1).active,false);});
test('disposing cancels active gate and stops participant',async()=>{const x=setup();x.monitor.begin(x.exec);x.monitor.togglePause();const pending=x.monitor.gate(x.exec);x.monitor.dispose();await assert.rejects(pending,/STOPPED/);assert.equal(x.monitor.agents.size,0);assert.equal(x.cancels(),1);});

test('pause requested during a running action is honest until that action settles',async()=>{const x=setup();x.monitor.begin(x.exec);await x.monitor.gate(x.exec);x.monitor.togglePause();assert.equal(x.frames.at(-1).state,'pausing');assert.equal(x.frames.at(-1).executing,true);x.monitor.result(x.exec,{isError:false});assert.equal(x.frames.at(-1).state,'paused');assert.equal(x.frames.at(-1).executing,false);});
test('an idle participant releases its own paused gate without stranding other agents',async()=>{const x=setup();const other={...x.exec,agent:{id:'b',cancel(){}}};x.monitor.begin(x.exec);x.monitor.begin(other);x.monitor.togglePause();const a=x.monitor.gate(x.exec);let b=false;const pending=x.monitor.gate(other).then(()=>{b=true;});x.monitor.idle(x.agent);await assert.rejects(a,/STOPPED/);await tick();assert.equal(b,false);x.monitor.togglePause();await pending;assert.equal(b,true);});
test('idle without a final tool event clears active and executing states',async()=>{const x=setup();x.monitor.begin(x.exec);await x.monitor.gate(x.exec);x.monitor.idle(x.agent);assert.equal(x.frames.at(-1).state,'idle');assert.equal(x.frames.at(-1).active,false);assert.equal(x.frames.at(-1).executing,false);assert.equal(x.frames.at(-1).canStop,false);});
test('stopping is idempotent and a new turn can run after idle',async()=>{const x=setup();x.monitor.begin(x.exec);x.monitor.stop();x.monitor.stop();assert.equal(x.cancels(),1);x.monitor.idle(x.agent);const next={...x.exec,callId:'next',signal:new AbortController().signal};x.monitor.begin(next);await x.monitor.gate(next);assert.equal(x.frames.at(-1).state,'running');});
test('Cua nested target resolves a list_windows title, not arbitrary input text',()=>{const x=setup();x.exec.name='mcp__cua_native__list_windows';x.exec.arguments={};x.monitor.begin(x.exec);x.monitor.result(x.exec,{isError:false,value:{structuredContent:{windows:[{pid:123,window_id:456,title:'真实窗口'}]}}});const next={...x.exec,callId:'next',name:'mcp__cua_native__click',arguments:{target:{kind:'window',pid:123,window_id:456},text:'PRIVATE_INPUT'}};x.monitor.begin(next);assert.equal(x.frames.at(-1).target,'真实窗口');assert.equal(x.frames.at(-1).lastTool,'mcp__cua_native__click');});
test('Wincu observed HWND and child id retain only parent window title',()=>{const x=setup();const next=(callId,name,args)=>({...x.exec,callId,name:'mcp__wincu__windows_computer_use_'+name,arguments:args});const windows=next('windows','list_windows',{});x.monitor.begin(windows);x.monitor.result(windows,{isError:false,value:{content:[{type:'text',text:JSON.stringify({ok:true,windows:[{id:'uia:rt:1',nativeWindowHandle:456,name:'验收窗口'}]})}]}});const find=next('find','find',{nativeWindowHandle:456,query:'PRIVATE_QUERY'});x.monitor.begin(find);x.monitor.result(find,{isError:false,value:{structuredContent:{ok:true,results:[{id:'uia:rt:2',controlType:'Edit',name:'PRIVATE_INPUT',value:'PRIVATE_VALUE'}]}}});const click=next('click','click',{elementId:'uia:rt:2'});x.monitor.begin(click);assert.equal(x.frames.at(-1).target,'验收窗口');assert.doesNotMatch(JSON.stringify(x.frames),/PRIVATE_QUERY|PRIVATE_INPUT|PRIVATE_VALUE/);});
test('failed results cannot poison observed target cache',()=>{const x=setup();x.monitor.begin(x.exec);x.monitor.result(x.exec,{isError:true,value:{structuredContent:{window_title:'SECRET_ERROR',pid:123,window_id:456}}});x.monitor.begin({...x.exec,callId:'two'});assert.doesNotMatch(JSON.stringify(x.frames),/SECRET_ERROR/);});
test('only verified physical result coordinates are published as pointers',()=>{const x=setup();const run=(callId,name,value)=>{const exec={...x.exec,callId,name};x.monitor.begin(exec);x.monitor.result(exec,{isError:false,value:{structuredContent:value}});return x.frames.at(-1).pointer;};assert.deepEqual(run('1','mcp__wincu__windows_computer_use_click',{ok:true,action:'click',x:-400,y:70,method:'sendinput'}),{x:-400,y:70,space:'screen-physical',action:'click'});assert.equal(run('2','mcp__cua_native__click',{ok:true,action:'click',x:4,y:7,method:'sendinput'}),undefined);assert.equal(run('3','mcp__wincu__windows_computer_use_click',{ok:true,action:'click',x:4,y:7,method:'sendinput',homed:{dx:10,dy:20}}),undefined);assert.equal(run('4','mcp__wincu__windows_computer_use_click',{ok:true,action:'click',x:4,y:7,method:'background:Invoke'}),undefined);});
test('unknown prefix lookalikes are not admitted as observed tool names',()=>{const x=setup();assert.throws(()=>x.monitor.begin({...x.exec,name:'mcp__cua_native__SECRET_TOOL'}),/INVALID_CALL/);assert.deepEqual(x.frames,[]);});

test('stop reports stopping until the running action returns, then stopped',async()=>{const x=setup();x.monitor.begin(x.exec);await x.monitor.gate(x.exec);x.monitor.stop();assert.equal(x.frames.at(-1).state,'stopping');assert.equal(x.frames.at(-1).executing,true);x.monitor.result(x.exec,{isError:true});assert.equal(x.frames.at(-1).state,'stopped');assert.equal(x.frames.at(-1).executing,false);});
test('paused workflow shows paused while its next physical action waits',async()=>{const x=setup();const workflow={...x.exec,name:'workflow_replay',callId:'workflow'};x.monitor.begin(workflow);await x.monitor.gate(workflow);x.monitor.togglePause();x.monitor.begin(x.exec);const pending=x.monitor.gate(x.exec);assert.equal(x.frames.at(-1).state,'paused');x.monitor.stop();await assert.rejects(pending,/STOPPED/);});
